"""Fix LibraryItem model

Revision ID: 604e47819d05
Revises: 63af8ac38458
Create Date: 2025-02-03 12:25:49.981994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '604e47819d05'
down_revision: Union[str, None] = '63af8ac38458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('library_items', 'published_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('library_items', 'available_copies',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('library_items', 'available_copies',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('library_items', 'published_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
