"""Add available_copies field to library_items

Revision ID: 63af8ac38458
Revises: e04c146871d1
Create Date: 2025-02-03 07:10:20.670348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63af8ac38458'
down_revision: Union[str, None] = 'e04c146871d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library_items', sa.Column('available_copies', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library_items', 'available_copies')
    # ### end Alembic commands ###
