"""Fix LibraryItem schema

Revision ID: 94f2f90664b2
Revises: 604e47819d05
Create Date: 2025-02-03 12:31:55.538299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f2f90664b2'
down_revision: Union[str, None] = '604e47819d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('published_year', sa.Integer(), nullable=False))
    op.drop_column('books', 'publish_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publish_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('books', 'published_year')
    # ### end Alembic commands ###
